### ISSUE TITLE
Telescope 无法查找符号

### ISSUE THREAD

**Issue by OOSYOO** [Campanula/dotfiles#1]
hello，请教一个neovim的问题：
打开cpp文件，运行
`:Telescope lsp_document_symbols`会出现弹窗错误
`[telescope.builtin.lsp_*]: server does not support documentSymbolProvider`

请问有什么解决办法吗？

**Comment by chaneyzorn** [comment]
@OOSYOO 感觉需要先确认你使用的 cpp 的 lsp-server 是哪一个？

**Comment by OOSYOO** [comment]
> @OOSYOO 感觉需要先确认你使用的 cpp 的 lsp-server 是哪一个？

clangd

**Comment by OOSYOO** [comment]
> @OOSYOO 感觉需要先确认你使用的 cpp 的 lsp-server 是哪一个？

是clangd，补全等功能都是可以用的。

**Comment by chaneyzorn** [comment]
![image](https://user-images.githubusercontent.com/8176642/201108933-7f91911f-2ce9-4d2a-b101-ea262ccdc5d2.png)


我这里没有复现
